### ISSUE TITLE
In window10, the result of utxt file's name is wrong!

### ISSUE THREAD

**Issue by DaSea** [scrooloose/vim-slumlord#1]
- the result is `VICE1C5.utxt`, but the plugin need `VICE1C5.tmp.utxt`, so need change the `mungeDiagramInTmpFile` function!*

```
function! s:mungeDiagramInTmpFile(fname) abort
    execute "write " . a:fname
    call s:convertNonAsciiSupportedSyntax(a:fname)
    let tmpname = fnamemodify(a:fname,  ':r')
    return tmpname . '.utxt'
endfunction
```

**Comment by scrooloose** [comment]
Wow, didn't know anyone else was actually using this thing :)

Have made that fix, thanks for the report.
