### ISSUE TITLE
Diagrams are saved to file

### ISSUE THREAD

**Issue by tecfu** [scrooloose/vim-slumlord#2]
### Observed Behavior:

The previewed diagram is actually written into the UML file on save.

### Expected Behavior:

The previewed diagram should not actually be saved into the UML file.

### OS: 

Ubuntu 14.04

### Vim Version:

8

### Comments:

Can't we just use a split window to do the preview instead?

**Comment by jon301** [comment]
This would be awesome so we wouldn't have to scroll up to see the result
Awesome plugin btw !!! :)

**Comment by scrooloose** [comment]
Hmm, I guess a design like this would work:

![updater](https://cloud.githubusercontent.com/assets/1671/20262923/518471ec-aa5c-11e6-9c74-d9e52ce9ed0d.png)

This will support both approaches - and whatever new ideas people have. Thoughts?

**Comment by tecfu** [comment]
Works for me.

**Comment by scrooloose** [comment]
This has (finally) be implemented in master.

Can be enabled with `let g:slumlord_separate_win=1` in your vimrc.

I'm thinking of making this the default and only way to render the diagram - as, after using it, it just seems to be superior.

**Comment by tecfu** [comment]
Thanks Martin.
