### ISSUE TITLE
Disable plantuml's splash screen

### ISSUE THREAD

**Issue by PhilRunninger** [scrooloose/vim-slumlord#4]
Great plugin, Martin! Just one suggestion though. I'm running this on a Mac with an external monitor, where iTerm/vim is running fullscreen. When I save the UML file, the Mac's screen switches to a non-fullscreen desktop when Java runs. I have to switch back to that fullscreen app every time the UML file is saved. That's super annoying, especially if it contains my reference material. 

It seems like Java is only doing that to display the plantuml splash screen. There's a command line switch to specify your own splash screen, and leaving it blank displays no splash screen at all. Modifying this line https://github.com/scrooloose/vim-slumlord/blob/master/autoload/slumlord.vim#L19 has done the trick for me, but I don't know if it's the correct way to go about it.

```
let cmd = "java -splash: -jar ". s:jar_path ." -tutxt " . tmpfname
```

**Comment by scrooloose** [comment]
Excellent! I had no idea this was possible.
