### ISSUE TITLE
Ending .pu should be recognized

### ISSUE THREAD

**Issue by derphilipp** [scrooloose/vim-slumlord#7]
Using the ending .pu as integrated in [an issue of plantuml-syntax](https://github.com/aklt/plantuml-syntax/issues/2) shoud be used in vim-slumlord too;

**Comment by scrooloose** [comment]
Just pushed the fix - let me know if there are any problems. Thanks :)

**Comment by derphilipp** [comment]
That was fast, thank you very much! Awesome project;

**Comment by scrooloose** [comment]
NP, glad it is useful!
